
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://santteegt.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /home

# Google tracking id

google-tracking-id: "UA-100006699-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Santiago Gonzalez Toral, MSc Eng"
title: "{ Santiago Gonzalez - Data Science Engineer }"
description: "Blog and website of Santiago Gonzalez Toral, blogging mainly for data science, machine learning, full stack development and tech. Opinions expressed are mine."
keywords: "santiago, gonzalez, toral, data, science, machine, learning, engineer, coding, deep, predictive, analytics, visualization, development"
favicon: "/img/favicon.ico"

################
# Header layout #
################

# black-favicon: "/img/black-lab-glass.ico"
black-favicon: "/img/favicon.ico"

background-img: "../img/intro.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 20
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Data Science is a Journey, not a destination"
  - text: "Telling my story as a Data Science Engineer"
  - text: "I'm as a computer geek, gamer, footballer and old school skateboarder"

# me-img: "/img/jetpacktocat.png"
me-img: "/img/profile-img.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "santigonzaleztoral"

syntax-highlight: True

hasBlogPosts: 0
blogPostsNotFound: "## Comming Soon"

###########
# My URLs #
###########

my_urls:
  cv: ''
  github: 'https://github.com/santteegt'
  stack-overflow-story: http://stackoverflow.com/story/santteegt

############
# Timeline #
############

events:
  - image: "/img/timeline/aigents_lab.png"
    date: "January 2017 - Today"
    description: "AIgents Lab - Big Data Science solutions"
    job_description: "Building my first startup"
    url: "https://santteegt.github.io/aigentslab/"
  - image: "/img/timeline/graduation.png"
    date: "November 2016"
    description: "MSc Web Science and Big Data Analytics"
    job_description: "Start of my career  as Data Science Engineer"
  - image: "/img/timeline/ucl.png"
    date: "September 2015"
    description: "Master programme at UCL"
    job_description: "5 years as Full Stack Developer"
  - image: "/img/timeline/open_data.png"
    date: "February 2014"
    description: "Open Data activist"
    job_description: "Research Assistant at DCC - University of Cuenca"
  - image: "/img/timeline/ucuenca.jpg"
    date: "October 2012"
    description: "System's Engineer"
    job_description: "Senior Consultant - 2 year experience as Software Developer"

# First image of the Timeline

timeline-img: "/img/timeline/start.jpeg"

#############
# Portfolio #
#############

hasPortfolio: 1
portfolioNotFound: "## Comming Soon"

###########
# Contact #
###########

email: "hernangt12re3@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Santiago Gonzalez is a Data Science Engineer and a Full Stack Developer with more than 6 years of experience. He is really passionate about tech, data & football."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/santygongt"
  - title: "twitter"
    url: "https://twitter.com/santteegt"
  - title: "instagram"
    url: "https://www.instagram.com/santteegt"
  - title: "github"
    url: "https://github.com/santteegt"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/santteegt"
  - title: "stack-overflow"
    url: "http://stackoverflow.com/story/santteegt"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: santteegt
keybase-in-social: True
keybase-in-footer: False

###############
# Footer info #
###############

footer:
  copyright: Santiago Gonzalez Toral, MSc Eng
  location: Current Location
  location_url: 'https://en.wikipedia.org/wiki/Cuenca,_Ecuador'
  social: Find me around the Web

# Postal address (add as many lines as necessary)
address:
  - line: Cuenca - Ecuador
  - line: EC010101

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Portfolio: 'portfolio'
  Blog: 'latest-post'
  Contact: 'contact'
  CV: 'cv'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
